### ISSUE TITLE
Issues in version 2.2

### ISSUE THREAD

**Issue by niraj-rayalla** [SrJohnathan/gdx-effekseer#7]
1. I cannot pull the commit that the Effekseer has been updated to (https://github.com/effekseer/Effekseer/tree/2e9601f372f631dceee731a17a0676777d6eeb29).

2. I have this exception at run time. For some reason SetTime() in EffekseerManagerCore is not available.
```
Exception in thread "GL Thread" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsatisfiedLinkError: io.github.srjohnathan.gdx.effekseer.core.GDXJNI.EffekseerManagerCore_SetTime(JLio/github/srjohnathan/gdx/effekseer/core/EffekseerManagerCore;F)V
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:122)
	at ...
Caused by: java.lang.UnsatisfiedLinkError: io.github.srjohnathan.gdx.effekseer.core.GDXJNI.EffekseerManagerCore_SetTime(JLio/github/srjohnathan/gdx/effekseer/core/EffekseerManagerCore;F)V
	at io.github.srjohnathan.gdx.effekseer.core.GDXJNI.EffekseerManagerCore_SetTime(Native Method)
	at io.github.srjohnathan.gdx.effekseer.core.EffekseerManagerCore.SetTime(EffekseerManagerCore.java:236)
	at io.github.srjohnathan.gdx.effekseer.wrapped.EffekseerManager.draw(EffekseerManager.java:351)
	...
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	... 1 more
```

**Comment by SrJohnathan** [comment]
in gradle and run the runSwig task to create a dll.cpp file, it will solve
the SetTime issue, I will commit and release a 2.2.1 version, fixes.
I have this problem, explain to me?

Caused by: com.badlogic.gdx.utils.GdxRuntimeException: No loader for type:
Result

Em ter., 5 de abr. de 2022 às 14:33, niraj-rayalla ***@***.***>
escreveu:

**Comment by niraj-rayalla** [comment]
Oh my bad. I forgot to add the following block of code in the readme.
You are probably getting that issue because you haven't added the loaders to your AssetManager instance.

Add this to your AssetManager instance before calling EffekseerParticle.syncLoad() or EffekseerParticle.asyncLoad()
```
assetManager.setLoader(EffekseerParticleSubAssetLoader.Result.class, null, new EffekseerParticleSubAssetLoader(fileHandleResolver));
assetManager.setLoader(EffekseerParticleAssetLoader.Result.class, null, new EffekseerParticleAssetLoader(fileHandleResolver));
```

I'll add it to the readme.

**Comment by niraj-rayalla** [comment]
Updated the readme in https://github.com/niraj-rayalla/gdx-effekseer/commit/012ec4decd164b75f3038ee62987c18053dc1d89

**Comment by niraj-rayalla** [comment]
I seem to have this issue in 2.2.2:

```
Exception in thread "GL Thread" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsatisfiedLinkError: io.github.srjohnathan.gdx.effekseer.core.GDXJNI.EffekseerBackendCore_InitializeAsOpenGL()Z
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:122)
Caused by: java.lang.UnsatisfiedLinkError: io.github.srjohnathan.gdx.effekseer.core.GDXJNI.EffekseerBackendCore_InitializeAsOpenGL()Z
	at io.github.srjohnathan.gdx.effekseer.core.GDXJNI.EffekseerBackendCore_InitializeAsOpenGL(Native Method)
	at io.github.srjohnathan.gdx.effekseer.core.EffekseerBackendCore.InitializeAsOpenGL(EffekseerBackendCore.java:44)
	at io.github.srjohnathan.gdx.effekseer.wrapped.EffekseerManager.<init>(EffekseerManager.java:75)
```

**Comment by SrJohnathan** [comment]
it's windows or linux this error, maybe it's windows, I must have forgotten
the new compiled dll file, I'll fix it, do you have Discord?

Em sáb, 7 de mai de 2022 20:56, niraj-rayalla ***@***.***>
escreveu:

**Comment by niraj-rayalla** [comment]
I emailed you.
